### ISSUE TITLE
Link header instead of envelope

### ISSUE THREAD

**Issue by pbrisbin** [eborden/yesod-page-cursor#1]
Rather than enveloping the response and putting the real data in a key like `.data`, WDYT of adding the pagination links as a `Link` header?

For [example](https://developer.github.com/v3/guides/traversing-with-pagination/):

```
Link: <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=2>; rel="next",
  <https://api.github.com/search/code?q=addClass+user%3Amozilla&page=34>; rel="last"
```

The Hackage packages [http-link-header](http://hackage.haskell.org/package/http-link-header) or [wreq](https://hackage.haskell.org/package/wreq-0.5.3.2/docs/Network-Wreq.html#v:responseLink) can both be used toe easily interact with such responses in Haskell clients. I imagine clients in other languages have similar features.

**Comment by eborden** [comment]
My thought here was to add a function that lifts that info into the `Header`.

```hs
toHeader :: MonadHandler m => Page a -> m [a]
```

That way the choice of `JSON` encoding or `Header` encoding is accessible.

**Comment by pbrisbin** [comment]
Makes total sense, thanks!
