### ISSUE TITLE
No reason to decode limit param as JSON

### ISSUE THREAD

**Issue by pbrisbin** [eborden/yesod-page-cursor#3]
Functionality is the same as you would expect: `&limit=100` -> `100`, but it's a bit unnecessary as we always expect this to be a scalar number. We could use `PathPiece`, `Read`. As long as we preserve a useful 400 error message in whatever we do.

**Comment by eborden** [comment]
I think I'd prefer `PathPiece` since it typically has better error messages.

**Comment by pbrisbin** [comment]
`fromPathPiece` is `Text -> Maybe a` so there's actually not much there. I'm not sure there's a class out there that'll give us good error messages out of the box.

Even using `FromJSON` leaves quite a bit to be desired:

```
λ> eitherDecode "whatnow" :: Either String Int
Left "Error in $: Failed reading: not a valid json value"
λ> eitherDecode "\"whatnow\"" :: Either String Int
Left "Error in $: expected Int, encountered String"
λ> eitherDecode "{}" :: Either String Int
Left "Error in $: expected Int, encountered Object"
λ> eitherDecode "[]" :: Either String Int
Left "Error in $: expected Int, encountered Array"
```

"Expected Int, encountered Blah" isn't super informative, and the "Error in $:" is going to be confusing to users in this context.

I think I lean towards a simple:

```hs
ourOwnDecode :: Text -> Either String Int
ourOwnDecode x = note (show x <> " must be a whole number") $ readMay $ unpack x
```

`fromPathPiece` is `readMay . unpack` (at `Int`) so maybe that's worthwhile?
:man_shrugging:

**Comment by eborden** [comment]
Arg, you are right. So there really is no benefit to `fromPathPiece` over `readMay`.
