### ISSUE TITLE
Remove domain from PageConfig

### ISSUE THREAD

**Issue by pbrisbin** [eborden/yesod-page-cursor#4]
We can grab the `Host` header from the `Request` directly as part of `getRenderedRoute` and not need this aspect of the config. This would reduce the config to a `newtype` over `(a -> position)`, which we could keep or just pass that function directly to `withPage`.

**Comment by eborden** [comment]
Looks like the proxy name is `X-Forwarded-Host`, which would be nice to support.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host
